# This is a basic workflow to help you get started with Actions

name: Pytest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Java
        run: |
          antlr4 -Dlanguage=Python3 project/language.g4 -visitor -o project/lang


      - name: Test with pytest
        run: |
          pip install pytest
          python ./scripts/run_tests.py
